### PR TITLE
POWR-3879 clean ups noticed in PR review.

### PR DESCRIPTION
**Pull request by joshuami**

### CODE REVIEW

**Comment by joshuami** [comment]
@RichardDavies , I didn't create a new story for it, but I did whip up some fixes to the issues you saw in POWR-3879 for you to add to the next deploy. I ended up going down a bit of a rabbit hole and adding a fontawesome feature as well. I can only imagine where editors will take it 😉

**Comment by RichardDavies** [comment]
Looks good, but did you intend to change the external link icon to a question mark?
image

Also, I noticed that mailto: links are showing the external link icon (e.g. /bts/cab) . We should probably turn that off for those links. 
image

**Comment by joshuami** [comment]
> Looks good, but did you intend to change the external link icon to a question mark?

Hmm. That's not right. I need to look into why that isn't rendering on the multidev in the same way it did on my local.

**Comment by joshuami** [comment]
Oh huh. That is Firefox specific. Sheesh. I'll do some research. Here's what it looks like in Chrome:

2022-04-14 at 9 42 AM

**Comment by joshuami** [comment]
Also... do you want to delete that image from your comment? That API is not public, but our open repo has an open issue and PR queue.

**Comment by joshuami** [comment]
Okay... found a fix. Firefox and Safari are both a bit more particular about how files are called. The Fontawesome 6 approach of using SVGs and JS doesn't play nice with those browsers without some additional CORS configuration or server headers. The font and CSS approach still works fine. I'm not seeing that there is an appreciable difference between the two, so I've switched it over. 

I also caught a reference to Typekit that we don't need while reviewing this and was able to remove an unneeded template.

You should be able to test again when the build finishes.

**Comment by joshuami** [comment]
Build is complete and the fix has cleared up the issue.

**Review by RichardDavies — APPROVED** [review]

**Pull request merged**
